// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoF-WJKySDeBJL-0BZctFCLa--DOGiDA4',
    appId: '1:743413057469:web:082b52e3de3e4dc9a174d4',
    messagingSenderId: '743413057469',
    projectId: 'fir-auth-f5804',
    authDomain: 'fir-auth-f5804.firebaseapp.com',
    storageBucket: 'fir-auth-f5804.appspot.com',
    measurementId: 'G-W344F295Q9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLAOjz6xmEsWn3cD49OcioWyh8Kw9aoYk',
    appId: '1:743413057469:android:fe0904c3d3b10bfea174d4',
    messagingSenderId: '743413057469',
    projectId: 'fir-auth-f5804',
    storageBucket: 'fir-auth-f5804.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfRl-b2ggbPHUjetm9GOklZ_SqxwM9zRw',
    appId: '1:743413057469:ios:d26d6de0e2d8503ba174d4',
    messagingSenderId: '743413057469',
    projectId: 'fir-auth-f5804',
    storageBucket: 'fir-auth-f5804.appspot.com',
    androidClientId: '743413057469-go72g7feohbdpqjk63terquqf0h4o6ob.apps.googleusercontent.com',
    iosClientId: '743413057469-snk38f8kkr46l5r8ieqrputrmebbde61.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

}