// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzaYCV28WXnxtapIe901lDpjHyqvI5KP8',
    appId: '1:979792986083:web:f19933977e04ab5963ead6',
    messagingSenderId: '979792986083',
    projectId: 'testingapplabu',
    authDomain: 'testingapplabu.firebaseapp.com',
    databaseURL: 'https://testingapplabu-default-rtdb.firebaseio.com',
    storageBucket: 'testingapplabu.appspot.com',
    measurementId: 'G-G3J5N09EQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI4usR_P7NDJfsT4oStOe60KSV39iV6yc',
    appId: '1:979792986083:android:00f4ed27ed2b6e7163ead6',
    messagingSenderId: '979792986083',
    projectId: 'testingapplabu',
    databaseURL: 'https://testingapplabu-default-rtdb.firebaseio.com',
    storageBucket: 'testingapplabu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8vVOjYZKoTTEMnPo-WUKbpDcymY1pJvs',
    appId: '1:979792986083:ios:6f8c13e85fe24c4763ead6',
    messagingSenderId: '979792986083',
    projectId: 'testingapplabu',
    databaseURL: 'https://testingapplabu-default-rtdb.firebaseio.com',
    storageBucket: 'testingapplabu.appspot.com',
    iosClientId: '979792986083-1uavdvmhs3e20goe1qhn198071oggcdb.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

}